In [1]:
import pandas as pd

data = {
    'nama': ['Hasan', 'Husein', 'Tiut', 'Titut', 'Asep'],
    'uts': [75, 85, 90, 70, 88],
    'uas': [88, 78, 90, 86, 100]
}

df_nilai = pd.DataFrame(data)
df_nilai['nilai_akhir'] = (df_nilai['uts'] * 0.4) + (df_nilai['uas'] * 0.6)

df_nilai

     nama  uts  uas  nilai_akhir
0   Hasan   75   88         82.8
1  Husein   85   78         80.8
2    Tiut   90   90         90.0
3   Titut   70   86         79.6
4    Asep   88  100         95.2

In [2]:
df_nilai_di_atas_80 = df_nilai[df_nilai['nilai_akhir'] > 80]
df_nilai_di_atas_80

     nama  uts  uas  nilai_akhir
0   Hasan   75   88         82.8
1  Husein   85   78         80.8
2    Tiut   90   90         90.0
4    Asep   88  100         95.2